### ISSUE TITLE
@todo before 1.0.0

### ISSUE THREAD

**Issue by davetgreen** [davetgreen/all-in-the-title#1]
- [x] Update WPCS to latest stable, and tidy up PHP accordingly
- [x] Run the widget through a HTML validator to check for markup issues
- [x] Run the widget through a screen reader to check for a11y issues
- [x] Create an add plugin assets (headers, icons)
- [x] Update `readme.txt` for WP.org visitors
- [x] Add `README.md` for GitHub visitors
- [x] Create a `CHANGELOG.md`
- [x] Configure GitHub-to-SVN deployment (see Deployer/10UP)
